// Arda Yiğit - Hazani
// config.cpp — Configuration File Manager Implementation
// Implements reading/writing of macman.conf, default generation, and
// accessor methods for configuration values.


#include "core/config.hpp"
#include "macman.hpp"
#include <fstream>
#include <sstream>
#include <filesystem>
#include <iostream>

namespace fs = std::filesystem;

namespace macman {

// --- Singleton Access ---

Config& Config::instance() {
    static Config instance;
    return instance;
}

// --- Set Default Values ---

void Config::set_defaults() {
    settings_["CacheDir"]          = macman::get_cache_dir();
    settings_["DBDir"]             = macman::get_db_dir();
    settings_["LogFile"]           = macman::get_log_file();
    settings_["ParallelDownloads"] = "4";
    settings_["Color"]             = "auto";
    settings_["Verbose"]           = "false";
}

// --- Load Configuration ---

bool Config::load(const std::string& path) {
    config_path_ = path.empty() ? macman::get_config_file() : path;
    set_defaults();

    std::ifstream file(config_path_);
    if (!file.is_open()) {
        // Config file doesn't exist yet — use defaults
        return true;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') continue;
        
        // Remove inline comments
        auto comment_pos = line.find('#');
        if (comment_pos != std::string::npos) {
            line = line.substr(0, comment_pos);
        }

        // Parse "Key = Value" format
        auto eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;

        std::string key = line.substr(0, eq_pos);
        std::string value = line.substr(eq_pos + 1);

        // Trim whitespace
        auto trim = [](std::string& s) {
            s.erase(0, s.find_first_not_of(" \t"));
            s.erase(s.find_last_not_of(" \t") + 1);
        };
        trim(key);
        trim(value);

        if (!key.empty()) {
            settings_[key] = value;
        }
    }

    return true;
}

// --- Save Configuration ---

bool Config::save(const std::string& path) const {
    std::string save_path = path.empty() ? config_path_ : path;
    
    // Ensure directory exists
    fs::path dir = fs::path(save_path).parent_path();
    if (!dir.empty() && !fs::exists(dir)) {
        fs::create_directories(dir);
    }

    std::ofstream file(save_path);
    if (!file.is_open()) {
        return false;
    }

    file << "#\n";
    file << "# macman configuration file\n";
    file << "# Generated by macman " << VERSION << "\n";
    file << "#\n\n";

    file << "# ── General Options ──────────────────────────────\n\n";
    
    for (const auto& [key, value] : settings_) {
        file << key << " = " << value << "\n";
    }

    return true;
}

// --- Create Default Config File ---

void Config::create_default(const std::string& path) const {
    std::string save_path = path.empty() ? macman::get_config_file() : path;
    
    fs::path dir = fs::path(save_path).parent_path();
    if (!dir.empty() && !fs::exists(dir)) {
        fs::create_directories(dir);
    }

    std::ofstream file(save_path);
    if (!file.is_open()) return;

    file << "#\n";
    file << "# " << PROGRAM_NAME << " configuration file\n";
    file << "# " << DESCRIPTION << "\n";
    file << "#\n\n";

    file << "# ── Directories ──────────────────────────────────\n";
    file << "CacheDir     = " << macman::get_cache_dir() << "\n";
    file << "DBDir        = " << macman::get_db_dir() << "\n";
    file << "LogFile      = " << macman::get_log_file() << "\n\n";

    file << "# ── Network ─────────────────────────────────────\n";
    file << "ParallelDownloads = 4\n\n";

    file << "# ── Output ──────────────────────────────────────\n";
    file << "Color   = auto\n";
    file << "Verbose = false\n";
}

// --- Getters ---

std::string Config::get_cache_dir() const {
    return get("CacheDir", macman::get_cache_dir());
}

std::string Config::get_db_dir() const {
    return get("DBDir", macman::get_db_dir());
}

std::string Config::get_log_file() const {
    return get("LogFile", macman::get_log_file());
}

int Config::get_parallel_downloads() const {
    try {
        return std::stoi(get("ParallelDownloads", "4"));
    } catch (...) {
        return 4;
    }
}

bool Config::get_color_enabled() const {
    std::string val = get("Color", "auto");
    return val != "never";
}

bool Config::get_verbose() const {
    return get("Verbose", "false") == "true";
}

std::string Config::get(const std::string& key, const std::string& default_val) const {
    auto it = settings_.find(key);
    return (it != settings_.end()) ? it->second : default_val;
}

// --- Setter ---

void Config::set(const std::string& key, const std::string& value) {
    settings_[key] = value;
}

} // namespace macman
